language: generic
services:
  - docker

branches:
  only:
    - main

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "web-futurizeme"
  env: "Webfuturizeme-env"
  bucket: "elasticbeanstalk-us-east-1-756442812649"
  bucket_path: "web-futurizeme"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: main
